language: python

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.9-dev"

install:
  - pip install six blist unittest2 pytz
  - python setup.py install
script: python tests/tests.py
